apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keda-domino.fullname" . }}
  labels:
    {{- include "keda-domino.labels" . | nindent 4 }}
data:
  TARGET_NAMESPACES: {{ join "," .Values.targetNamespace | quote }}
